spring:
  cloud:
    consul:
      discovery:
        datacenters:
          mall-product: c2
          moka: c2
          tag-center: c2
          scm-inventory-center: c1
          common-service: c2
db:
  mysql:
    write:
      host: cn-prod-1.db.doublefs.com
      port: 3306
      dbname: quality_service
      username: quality_service_rw
      password: ,FVdSj5ENFg1*n5]Z1NP
    read:
      host: cn-prod-1.db.doublefs.com
      port: 3306
      dbname: quality_service
      username: quality_service_ro
      password: X]KKpjHJRYCUHkrXOg>y

  redis:
    host: cn-qc-1.cache.doublefs.com
    port: 6379

  kafka:
    host: b-1.cn-prod-1.7l0obq.c2.kafka.cn-northwest-1.amazonaws.com.cn:9092,b-3.cn-prod-1.7l0obq.c2.kafka.cn-northwest-1.amazonaws.com.cn:9092,b-2.cn-prod-1.7l0obq.c2.kafka.cn-northwest-1.amazonaws.com.cn:9092

config:
  sentry:
    dsn: https://d2dbbaf478434aafa505580eaacb0ee7@sentry.intra.doublefs.com/54

xxl:
  job:
    admin:
      addresses: https://job-center.prod.doublefs.com/  # ### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
    executor:
      appname: xxl-job-quality-service # ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      address:
      ip: # ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      port: 9997 # ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      accessToken: # ### 执行器通讯TOKEN [选填]：非空时启用；
      logpath: # ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logretentiondays: 14 # ### 执行器日志保存天数 [选填] ：值大于3时生效，启用执行器Log文件定期清理功能，否则不生效；

# 发送飞书提醒的群
api:
  dmmDevNotifyRobot: https://open.feishu.cn/open-apis/bot/v2/hook/1eff0282-477c-49f7-a26d-641ebf76b286

# presto 配置
presto:
  user: hadoop
  url: jdbc:presto://us-presto-01:8889/hive/